remote_theme: "mmistakes/minimal-mistakes@4.24.0"
# https://github.com/mmistakes/minimal-mistakes
title: "Aniket's SUperfund site of a website"
description: "Test, testing, 1-2-3. 2023-11-24, 2114 hrs"
plugins: ['jekyll-include-cache']

